version: "3.8"

services:
  storer:
    image: semirm/findhotel-storer:1
    build:
      context: .
      dockerfile: cmd/storer/Dockerfile
    container_name: findhotel_storer
    ports:
      - "8001:8001"
    networks:
      - findhotel
  gateway:
    image: semirm/findhotel-gateway:1
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    container_name: findhotel_gateway
    command:
      - -storer_uri=findhotel_storer:8001
    ports:
      - "8000:8000"
    depends_on:
      - storer
    networks:
      - findhotel
networks:
  findhotel: