version: "3.8"

services:
  loader:
    image: semirm/findhotel-loader:1
    build:
      context: .
      dockerfile: cmd/loader/Dockerfile
    container_name: findhotel_loader
    command:
      - -connStr=host=findhotel_pg port=5432 dbname=findhotel_geo user=postgres password=postgres sslmode=disable
      - -path=/app-data/data_dump.csv
    depends_on:
      - db
      - redis
    volumes:
      - ./cmd/loader/data_dump.csv:/app-data/
    networks:
      - findhotel
  gateway:
    image: semirm/findhotel-gateway:1
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    container_name: findhotel_gateway
    ports:
      - "8000:8000"
    depends_on:
      - loader
    networks:
      - findhotel
  db:
    image: postgres:latest
    container_name: findhotel_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=findhotel_geo
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    container_name: findhotel_redis
    environment:
      - REDIS_PASSWORD=
    ports:
      - "6379:6379"
networks:
  findhotel: