version: "3.8"

services:
  importer:
    image: semirm/findhotel-importer:1
    build:
      context: .
      dockerfile: cmd/importer/Dockerfile
    container_name: findhotel_importer
    command:
      - -storer_uri=findhotel_storer:8002
    ports:
      - "8001:8001"
    depends_on:
      - storer
    networks:
      - findhotel
  storer:
    image: semirm/findhotel-storer:1
    build:
      context: .
      dockerfile: cmd/storer/Dockerfile
    container_name: findhotel_storer
    ports:
      - "8002:8002"
    networks:
      - findhotel
  gateway:
    image: semirm/findhotel-gateway:1
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    container_name: findhotel_gateway
    command:
      - -importer_uri=findhotel_importer:8001
    ports:
      - "8000:8000"
    depends_on:
      - importer
    networks:
      - findhotel
networks:
  findhotel: