version: "3.8"

services:
  loader:
    image: semirm/findhotel-loader:1
    build:
      context: .
      dockerfile: cmd/loader/Dockerfile
    container_name: findhotel_loader
    command:
      - -storer_uri=findhotel_storer:8001
    depends_on:
      - storer
    networks:
      - findhotel
  storer:
    image: semirm/findhotel-storer:1
    build:
      context: .
      dockerfile: cmd/storer/Dockerfile
    container_name: findhotel_storer
    ports:
      - "8001:8001"
    networks:
      - findhotel
  gateway:
    image: semirm/findhotel-gateway:1
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    container_name: findhotel_gateway
    ports:
      - "8000:8000"
    depends_on:
      - loader
    networks:
      - findhotel
networks:
  findhotel: